name: Bug Report
description: Report a bug in arXiv Explorer
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the information below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `uv run axp ...`
        2. ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened. Include any error messages or tracebacks.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`.
      placeholder: "e.g., 3.12.0"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your operating system and version.
      placeholder: "e.g., Ubuntu 24.04, macOS 15.2, Windows 11"
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: arXiv Explorer Version
      description: Output of `uv run axp --version` or the version in pyproject.toml.
      placeholder: "e.g., 0.1.0"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem (logs, screenshots, configuration, etc.).
      placeholder: Add any other context here...
    validations:
      required: false
